development:
  adapter: postgresql
  database: ninety_nine_cats_dev
  host: 127.0.0.1
  pool: 5
  timeout: 5000

test:
    adapter: postgresql
    database: music_db_test
    pool: 5
    timeout: 5000
